import type { Metadata } from "next";
// ✨ 1. Import Roboto alongside Poppins
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/layout/Navbar";

// Configure Poppins font
export const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins', // A CSS variable name
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

// Configure Roboto font
export const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto', // A CSS variable name
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: "Youssafer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto.variable} scroll-smooth`}>
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
